export const PRODUCTS_DATA = {
  PRODUCTS: "PRODUCTS",
  PRODUCT_DATA_UPDATE: "PRODUCT_DATA_UPDATE",
  PRODUCT_RESET_STATE: "PRODUCT_RESET_STATE",
  PRODUCTS_VARIATION: "products/fetchProductVariations",
};
